#!/usr/bin/env python3
"""Generate a Markdown mirror of every page in sitemap.xml and list them in llms.txt.

    python3 scripts/build-markdown-mirrors.py           # write the mirrors and the llms.txt block
    python3 scripts/build-markdown-mirrors.py --check   # exit 1 if anything is missing or stale

For each sitemap URL ending in /, the page at <path>/index.html gets a mirror at <path>/index.md.
The HTML stays canonical. The mirror is a pure function of the HTML, so --check can compare
byte for byte, and site-deploy refuses to push while any mirror is stale.

GitHub Pages runs Jekyll on this repo, and Jekyll turns a .md file with YAML front matter into
an HTML page, which would overwrite the real index.html. The mirrors must therefore never start
with "---". Plain .md files are copied as-is and served as text/markdown.

Standard library only, so it runs unchanged on the VM and on the Mac.
"""
import re
import sys
import xml.etree.ElementTree as ET
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import urljoin, urlparse

ROOT = Path(__file__).resolve().parent.parent
MARKER = "<!-- markdown-mirror: generated by scripts/build-markdown-mirrors.py, do not edit -->"
LLMS_START = "<!-- markdown-mirrors:start -->"
LLMS_END = "<!-- markdown-mirrors:end -->"

VOID = {"area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "source", "track", "wbr"}
DROP = {"script", "style", "noscript", "template", "svg", "button", "nav", "form", "iframe", "canvas"}
BLOCK = {
    "address", "article", "aside", "blockquote", "details", "div", "dl", "dd", "dt", "fieldset",
    "figcaption", "figure", "footer", "h1", "h2", "h3", "h4", "h5", "h6", "header", "hr", "li",
    "main", "ol", "p", "pre", "section", "summary", "table", "tr", "ul", "video",
}
# Blocks whose whole content is rendered as one line of inline text.
LEAF = {"p", "h1", "h2", "h3", "h4", "h5", "h6", "summary", "figcaption", "dt", "dd"}
# Closing one of these before more text means the two were laid out apart on the page.
SEPARATED = {"span", "small", "b", "strong", "time", "bdi", "i", "em", "a", "img"}
NO_SPACE_BEFORE = tuple(".,;:!?)]}'’\"%")


class Node:
    def __init__(self, tag, attrs, parent=None):
        self.tag, self.attrs, self.parent, self.children = tag, dict(attrs), parent, []


class TreeBuilder(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.root = Node("#root", {})
        self.cur = self.root

    def handle_starttag(self, tag, attrs):
        node = Node(tag, attrs, self.cur)
        self.cur.children.append(node)
        if tag not in VOID:
            self.cur = node

    def handle_startendtag(self, tag, attrs):
        self.cur.children.append(Node(tag, attrs, self.cur))

    def handle_endtag(self, tag):
        node = self.cur
        while node is not self.root and node.tag != tag:
            node = node.parent
        if node is not self.root:
            self.cur = node.parent

    def handle_data(self, data):
        self.cur.children.append(data)


def find(node, pred):
    if isinstance(node, str):
        return None
    if pred(node):
        return node
    for child in node.children:
        hit = find(child, pred)
        if hit:
            return hit
    return None


def find_all(node, pred, out=None):
    out = [] if out is None else out
    if isinstance(node, Node):
        if pred(node):
            out.append(node)
        for child in node.children:
            find_all(child, pred, out)
    return out


def text_of(node):
    if isinstance(node, str):
        return node
    return "".join(text_of(c) for c in node.children)


def squash(s):
    return re.sub(r"\s+", " ", s).strip()


class Renderer:
    def __init__(self, page_url, root):
        self.page_url = page_url
        self.ids = {n.attrs["id"]: n for n in find_all(root, lambda n: "id" in n.attrs)}

    def skip(self, node):
        if node.tag in DROP or node.attrs.get("aria-hidden") == "true":
            return True
        # data-*-caption elements hold the animation's running caption, a repeat of text on the page.
        if any(k.startswith("data-") and k.endswith("-caption") for k in node.attrs):
            return True
        cls = node.attrs.get("class", "").split()
        if node.tag == "a" and "button" in cls and node.attrs.get("href", "").startswith("#"):
            return True  # an in-page jump button means nothing outside the page
        return "skip-link" in cls or "site-header" in cls or "site-footer" in cls

    def words(self, node):
        """The visible text pieces under a node, one per text-bearing element."""
        pieces = []
        for child in node.children:
            if isinstance(child, str):
                if child.strip():
                    pieces.append(squash(child))
            elif not self.skip(child):
                pieces.extend(self.words(child))
        return pieces

    def url(self, href):
        return urljoin(self.page_url, href.strip())

    # ---- inline ----------------------------------------------------------------
    def inline(self, nodes, in_heading=False):
        out = []
        pending_sep = False

        def emit(s):
            nonlocal pending_sep
            if not s:
                return
            if pending_sep and out:
                prev = out[-1]
                if not prev[-1:].isspace() and not s[:1].isspace() and not s.startswith(NO_SPACE_BEFORE) \
                        and not prev.endswith(("(", "[", "/")):
                    out.append(" ")
            pending_sep = False
            out.append(s)

        for node in nodes:
            if isinstance(node, str):
                emit(re.sub(r"\s+", " ", node).replace("*", r"\*"))
                continue
            if self.skip(node):
                continue
            tag = node.tag
            if tag == "br":
                emit(" " if in_heading else "  \n")
                continue
            if tag == "img":
                alt = squash(node.attrs.get("alt", ""))
                if alt:
                    emit(f"![{alt}]({self.url(node.attrs.get('src', ''))})")
                    pending_sep = True
                continue
            inner = self.inline(node.children, in_heading)
            if tag in BLOCK:
                # A block nested inside a leaf (rare in this markup) reads as its own sentence.
                inner = inner.strip()
                if inner:
                    emit((" " if out else "") + inner)
                pending_sep = True
                continue
            stripped = inner.strip()
            if not stripped:
                if inner:
                    emit(" ")
                continue
            lead = " " if inner[:1].isspace() else ""
            trail = " " if inner[-1:].isspace() else ""
            if tag in ("strong", "b") and not in_heading and "**" not in stripped:
                stripped = f"**{stripped}**"
            elif tag in ("em", "i") and not in_heading and "*" not in stripped.replace(r"\*", ""):
                stripped = f"*{stripped}*"
            elif tag == "a":
                href = node.attrs.get("href", "")
                if href and not href.startswith(("#", "javascript:")):
                    target = self.url(href)
                    stripped = f"<{target}>" if stripped == target else f"[{stripped}]({target})"
            emit(lead + stripped + trail)
            if tag in SEPARATED:
                pending_sep = True
        return "".join(out)

    # ---- blocks ----------------------------------------------------------------
    def blocks(self, node, list_depth=0):
        """Render a node's children as a list of Markdown blocks."""
        out, run = [], []

        def flush():
            text = self.inline(run).strip()
            if text:
                out.append(text)
            run.clear()

        for child in node.children:
            if isinstance(child, str) or (child.tag not in BLOCK and not self.skip(child)):
                run.append(child)
                continue
            if self.skip(child):
                continue
            flush()
            out.extend(self.block(child, list_depth))
        flush()
        return out

    def block(self, node, list_depth):
        tag = node.tag
        if tag in ("h1", "h2", "h3", "h4", "h5", "h6"):
            text = squash(self.inline(node.children, in_heading=True))
            if not text:
                return []
            if list_depth:
                return [f"**{text}**"]
            return ["#" * int(tag[1]) + " " + text]
        if tag in ("ul", "ol"):
            items, n = [], 0
            for li in node.children:
                if isinstance(li, str) or li.tag != "li" or self.skip(li):
                    continue
                n += 1
                bullet = f"{n}. " if tag == "ol" else "- "
                body = self.blocks(li, list_depth + 1)
                if tag == "ol" and body and re.fullmatch(r"\d+\.?", body[0]):
                    body = body[1:]  # a visible "01" counter duplicates the list number
                if not body:
                    continue
                pad = " " * len(bullet)
                lines = "\n\n".join(body).split("\n")
                items.append(bullet + lines[0] + "".join("\n" + (pad + l if l else "") for l in lines[1:]))
            return ["\n".join(items)] if items else []
        if tag == "hr":
            return ["---"]
        if tag == "video":
            label = squash(node.attrs.get("aria-label") or node.attrs.get("title") or "")
            return [f"*Video: {label}*"] if label else []
        if tag == "summary":
            text = squash(self.inline(node.children, in_heading=True))
            return [f"**{text}**"] if text else []
        if tag == "blockquote":
            body = "\n\n".join(self.blocks(node, list_depth))
            return ["\n".join("> " + l if l else ">" for l in body.split("\n"))] if body else []
        if tag in LEAF:
            text = self.inline(node.children).strip()
            text = re.sub(r"[ \t]+\n", "  \n", text)
            return [text] if text else []
        out = []
        if node.attrs.get("role") == "tabpanel":
            # The tab buttons are dropped, so carry the tab's label in as the panel's title.
            tab = self.ids.get(node.attrs.get("aria-labelledby", ""))
            if tab is not None:
                label = ": ".join(self.words(tab))
                if label:
                    out.append(f"**{label}**")
        return out + self.blocks(node, list_depth)


def meta(root, name=None, prop=None):
    node = find(root, lambda n: n.tag == "meta" and (
        (name and n.attrs.get("name") == name) or (prop and n.attrs.get("property") == prop)))
    return squash(node.attrs.get("content", "")) if node else ""


def page_info(html_path, page_url):
    builder = TreeBuilder()
    builder.feed(html_path.read_text(encoding="utf-8"))
    root = builder.root
    title_node = find(root, lambda n: n.tag == "title")
    title = squash(text_of(title_node)) if title_node else page_url
    canonical = find(root, lambda n: n.tag == "link" and n.attrs.get("rel") == "canonical")
    canonical = canonical.attrs.get("href", page_url) if canonical else page_url
    main = find(root, lambda n: n.tag == "main") or find(root, lambda n: n.tag == "body") or root
    return root, title, canonical, main


def render_mirror(html_path, page_url):
    root, title, canonical, main = page_info(html_path, page_url)
    description = meta(root, name="description")
    body = "\n\n".join(Renderer(page_url, root).blocks(main))
    body = re.sub(r"\n{3,}", "\n\n", body)
    header = [MARKER, "", f"> Markdown version of {canonical}", "> The HTML page is the canonical source.", ""]
    header += [f"Title: {title}"]
    if description:
        header += [f"Description: {description}"]
    text = "\n".join(header) + "\n\n" + body.strip() + "\n"
    assert not text.startswith("---"), "front matter would make Jekyll overwrite index.html"
    return text, title


def declares_mirror(html_path, md_url):
    """True if the page's <head> points agents at its mirror with a text/markdown alternate link."""
    root = page_info(html_path, md_url)[0]
    return find(root, lambda n: n.tag == "link" and n.attrs.get("rel") == "alternate"
                and n.attrs.get("type") == "text/markdown" and n.attrs.get("href") == md_url) is not None


def sitemap_pages():
    tree = ET.parse(ROOT / "sitemap.xml")
    ns = {"s": "http://www.sitemaps.org/schemas/sitemap/0.9"}
    pages = []
    for loc in tree.getroot().findall("s:url/s:loc", ns):
        url = loc.text.strip()
        path = urlparse(url).path
        if not path.endswith("/"):
            sys.exit(f"ERROR: sitemap URL {url} does not end in /; only directory pages are supported")
        rel = path.lstrip("/")
        pages.append((url, ROOT / rel / "index.html", ROOT / rel / "index.md", urljoin(url, "index.md")))
    return pages


def llms_label(llms_text, url, fallback):
    """Reuse the hand-written label from llms.txt ("- Executive profile: <url>") when there is one."""
    outside = re.sub(re.escape(LLMS_START) + r".*?" + re.escape(LLMS_END), "", llms_text, flags=re.S)
    m = re.search(r"^- (.+?):\s*" + re.escape(url) + r"\s*$", outside, flags=re.M)
    return m.group(1) if m else fallback


def render_llms(llms_text, entries):
    lines = [LLMS_START, "## Markdown versions", "",
             "Plain Markdown copies of the canonical pages, regenerated from the HTML at every deploy. "
             "The HTML pages remain the canonical sources.", ""]
    lines += [f"- [{llms_label(llms_text, url, title)}]({md_url})" for url, md_url, title in entries]
    lines.append(LLMS_END)
    block = "\n".join(lines)
    if LLMS_START in llms_text:
        return re.sub(re.escape(LLMS_START) + r".*?" + re.escape(LLMS_END), lambda _: block, llms_text, flags=re.S)
    # First run: put the block just before the closing navigation-aid note, or at the end.
    anchor = "This file is a navigation aid."
    if anchor in llms_text:
        return llms_text.replace(anchor, block + "\n\n" + anchor, 1)
    return llms_text.rstrip("\n") + "\n\n" + block + "\n"


def main(argv):
    check = "--check" in argv
    problems, writes, entries = [], [], []
    expected = set()
    for url, html_path, md_path, md_url in sitemap_pages():
        if not html_path.exists():
            problems.append(f"{url} is in sitemap.xml but {html_path.relative_to(ROOT)} does not exist")
            continue
        if not declares_mirror(html_path, md_url):
            problems.append(f'{html_path.relative_to(ROOT)} lacks <link rel="alternate" type="text/markdown" '
                            f'href="{md_url}"> in its <head>; add it by hand (for /he/, in the Hebrew build template)')
        text, title = render_mirror(html_path, url)
        expected.add(md_path)
        entries.append((url, md_url, title))
        if not md_path.exists() or md_path.read_text(encoding="utf-8") != text:
            writes.append((md_path, text))

    # A mirror whose page left the sitemap is stale too.
    for md_path in ROOT.rglob("index.md"):
        if ".git" in md_path.parts or md_path in expected:
            continue
        if md_path.read_text(encoding="utf-8").startswith(MARKER):
            writes.append((md_path, None))

    llms_path = ROOT / "llms.txt"
    llms_text = llms_path.read_text(encoding="utf-8")
    new_llms = render_llms(llms_text, entries)
    if new_llms != llms_text:
        writes.append((llms_path, new_llms))

    for msg in problems:
        print("ERROR:", msg, file=sys.stderr)
    if check:
        for path, text in writes:
            state = "orphaned (page left the sitemap)" if text is None else "missing or stale"
            print(f"STALE: {path.relative_to(ROOT)} is {state}", file=sys.stderr)
        if writes:
            print("Run: python3 scripts/build-markdown-mirrors.py, review the diff, commit, then deploy.",
                  file=sys.stderr)
        if writes or problems:
            return 1
        print(f"markdown mirrors OK: {len(entries)} pages, llms.txt in sync")
        return 0
    for path, text in writes:
        if text is None:
            path.unlink()
            print("removed", path.relative_to(ROOT))
        else:
            path.write_text(text, encoding="utf-8")
            print("wrote  ", path.relative_to(ROOT))
    if not writes:
        print(f"nothing to do: {len(entries)} mirrors and llms.txt already in sync")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
